# .github/workflows/release.yml
name: Release to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    #step 1 : Get code
    - uses: actions/checkout@v2
    
    #step 2 : Set up Python 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    #step 3 : Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    #step 4 : Build package
    - name: Build package
      run: |
        python -m build
    
    #step 5 : Publish to PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*